### PR TITLE
Fixes #174

### LINKED ISSUE #174: Ensure concept sets across cohort definitions are unique
Facing an issue whereby a list of cohort definitions have the same concept set expression but different concept set IDs is causing the orphan concept checker in Cohort Diagnostics to fail. Reason being is that while the concept set expression is unique, the resulting SQL may differ since the conceptSetId is included as part of the SQL. Tracing through the code, this appears to be the offending code:

https://github.com/OHDSI/CohortDiagnostics/blob/master/R/ConceptSets.R#L239-L241 

@gowthamrao per our discussion, this will require some revision.

### PR DESCRIPTION
**Pull request by anthonysena**
Fixes #174

### CODE REVIEW

File: R/ConceptSets.R [hunk 1]
```diff
@@ -237,10 +237,10 @@ runConceptSetDiagnostics <- function(connection,
   
   conceptSets <- compareAndCombineConceptSetsDefinitionForCohorts(subset)
   uniqueConceptSets <- conceptSets %>% 
-                        dplyr::select(.data$uniqueConceptSetId, .data$conceptSetName, .data$conceptSetSql) %>% 
-                        dplyr::distinct()
-  instantiateUniqueConceptSets(cohorts = subset,
```
Comment (anthonysena) [inline R/ConceptSets.R:242]: I also removed the `cohorts = subset` parameter here since this appears to have been removed and was causing an error.
