### PR TITLE
Updates to docs and news to fix presentation

### LINKED ISSUE #722: Change vignette so cohortDatabaseSchema = cohortDatabaseSchema
https://github.com/OHDSI/CohortDiagnostics/blob/692c97c54f555f1e2a3e2e851abfc042596cd5d1/vignettes/RunningCohortDiagnostics.Rmd#L124

vignette has cdmDatabaseSchema as parameter.  those of us who mindlessly execute instructions will get an error :)

### LINKED ISSUE #723: Unclear what inclusionStatisticsFolder should be set to or if its needed
https://github.com/OHDSI/CohortDiagnostics/blob/692c97c54f555f1e2a3e2e851abfc042596cd5d1/vignettes/RunningCohortDiagnostics.Rmd#L153

This parameter was not described in vignette.  I commented it out to execute, not sure if this was replaced with CohortGenerator step?

### LINKED ISSUE #724: Add empty lines to NEWS.md so lists are rendered correctly
The [changelog on the package website](https://ohdsi.github.io/CohortDiagnostics/news/index.html) looks awful, because there are no empty lines before the lists in the markdown. Please add them.

### PR DESCRIPTION
**Pull request by azimov**
Closes #724
Closes #723
Closes #722 

Fixes docs and news.md format. Starts release 2.2.1

### CODE REVIEW

File: extras/PackageMaintenance.R [hunk 1]
```diff
@@ -57,6 +52,18 @@ rmarkdown::render("vignettes/RunningCohortDiagnostics.Rmd",
 pkgdown::build_site()
 OhdsiRTools::fixHadesLogo()
 
+# Change shiny app version number to current version
+pattern <- "Version: (\\d+\\.\\d+\\.\\d+)"
```
Comment (gowthamrao) [inline extras/PackageMaintenance.R:56]: nice!

**Review by gowthamrao — APPROVED** [review]
